name: PHP Code Style
on: [push, pull_request]
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    name: PHP Coding Standards Fixer
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - run: docker-compose up -d
      - run: composer install --prefer-dist
      - run: php vendor/bin/phpcs ./src
